# Generated by Django 3.2.9 on 2021-11-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211109_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='category',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='category',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
