# Generated by Django 3.2.9 on 2021-11-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211110_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='./default.jpg', upload_to='movies/movies/images'),
        ),
    ]
