# Generated by Django 3.2.9 on 2021-11-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='catagory',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='movies.Category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='movies/default.jpg', upload_to='movies/movies/images'),
        ),
    ]
