# Generated by Django 3.2.9 on 2021-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20211110_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='catagory',
        ),
        migrations.AddField(
            model_name='category',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='movies.Movie'),
        ),
    ]
