# Generated by Django 3.2.9 on 2021-11-10 14:20

from django.db import migrations, models
#

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=''),
        ),
    ]
